package ru.bmstu.rk6.cell.stub;


/**
* Cell/duplicateTubeExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

abstract public class duplicateTubeExceptionHelper
{
  private static String  _id = "IDL:Cell/duplicateTubeException:1.0";

  public static void insert (org.omg.CORBA.Any a, ru.bmstu.rk6.cell.stub.duplicateTubeException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ru.bmstu.rk6.cell.stub.duplicateTubeException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (ru.bmstu.rk6.cell.stub.duplicateTubeExceptionHelper.id (), "duplicateTubeException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ru.bmstu.rk6.cell.stub.duplicateTubeException read (org.omg.CORBA.portable.InputStream istream)
  {
    ru.bmstu.rk6.cell.stub.duplicateTubeException value = new ru.bmstu.rk6.cell.stub.duplicateTubeException ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ru.bmstu.rk6.cell.stub.duplicateTubeException value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
