package ru.bmstu.rk6.cell.stub;


/**
* Cell/TubeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public interface TubeOperations 
{
  void showMessage (String fromNumber, String text);
} // interface TubeOperations
