package ru.bmstu.rk6.cell.stub;


/**
* Cell/DataBasePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public abstract class DataBasePOA extends org.omg.PortableServer.Servant
 implements ru.bmstu.rk6.cell.stub.DataBaseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerStation", new java.lang.Integer (0));
    _methods.put ("registerTube", new java.lang.Integer (1));
    _methods.put ("getStationByTube", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Cell/DataBase/registerStation
       {
         String stationName = in.read_string ();
         boolean $result = false;
         $result = this.registerStation (stationName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Cell/DataBase/registerTube
       {
         String stationName = in.read_string ();
         String tubeName = in.read_string ();
         boolean $result = false;
         $result = this.registerTube (stationName, tubeName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Cell/DataBase/getStationByTube
       {
         String tubeName = in.read_string ();
         String receiverName = in.read_string ();
         String $result = null;
         $result = this.getStationByTube (tubeName, receiverName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Cell/DataBase:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DataBase _this() 
  {
    return DataBaseHelper.narrow(
    super._this_object());
  }

  public DataBase _this(org.omg.CORBA.ORB orb) 
  {
    return DataBaseHelper.narrow(
    super._this_object(orb));
  }


} // class DataBasePOA
