package ru.bmstu.rk6.cell.stub;

/**
* Cell/duplicateTubeExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public final class duplicateTubeExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ru.bmstu.rk6.cell.stub.duplicateTubeException value = null;

  public duplicateTubeExceptionHolder ()
  {
  }

  public duplicateTubeExceptionHolder (ru.bmstu.rk6.cell.stub.duplicateTubeException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ru.bmstu.rk6.cell.stub.duplicateTubeExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ru.bmstu.rk6.cell.stub.duplicateTubeExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ru.bmstu.rk6.cell.stub.duplicateTubeExceptionHelper.type ();
  }

}
