package ru.bmstu.rk6.cell.stub;


/**
* Cell/duplicateTubeException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public final class duplicateTubeException extends org.omg.CORBA.UserException
{

  public duplicateTubeException ()
  {
    super(duplicateTubeExceptionHelper.id());
  } // ctor


  public duplicateTubeException (String $reason)
  {
    super(duplicateTubeExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class duplicateTubeException
