package ru.bmstu.rk6.cell.stub;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public interface StationOperations 
{
  boolean registerTube (String number);
  boolean sendMessage (String fromNumber, String toNumber, String text);
  boolean sendInterMessage (String fromNumber, String toNumber, String fromStation, String text);
} // interface StationOperations
