package ru.bmstu.rk6.cell.stub;


/**
* Cell/TubeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

abstract public class TubeHelper
{
  private static String  _id = "IDL:Cell/Tube:1.0";

  public static void insert (org.omg.CORBA.Any a, ru.bmstu.rk6.cell.stub.Tube that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ru.bmstu.rk6.cell.stub.Tube extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ru.bmstu.rk6.cell.stub.TubeHelper.id (), "Tube");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ru.bmstu.rk6.cell.stub.Tube read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TubeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ru.bmstu.rk6.cell.stub.Tube value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ru.bmstu.rk6.cell.stub.Tube narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ru.bmstu.rk6.cell.stub.Tube)
      return (ru.bmstu.rk6.cell.stub.Tube)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ru.bmstu.rk6.cell.stub._TubeStub stub = new ru.bmstu.rk6.cell.stub._TubeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ru.bmstu.rk6.cell.stub.Tube unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ru.bmstu.rk6.cell.stub.Tube)
      return (ru.bmstu.rk6.cell.stub.Tube)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ru.bmstu.rk6.cell.stub._TubeStub stub = new ru.bmstu.rk6.cell.stub._TubeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
