package Cell;


/**
* Cell/TubeCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Thursday, December 8, 2011 12:51:51 PM MSK
*/


/* Интерфейс обратного вызова трубки */
public interface TubeCallback extends TubeCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TubeCallback
