package ru.bmstu.rk6.cell.stub;


/**
* Cell/lowBalanceException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public final class lowBalanceException extends org.omg.CORBA.UserException
{

  public lowBalanceException ()
  {
    super(lowBalanceExceptionHelper.id());
  } // ctor


  public lowBalanceException (String $reason)
  {
    super(lowBalanceExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class lowBalanceException
