package ru.bmstu.rk6.cell.stub;


/**
* Cell/StationPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public abstract class StationPOA extends org.omg.PortableServer.Servant
 implements ru.bmstu.rk6.cell.stub.StationOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerTube", new java.lang.Integer (0));
    _methods.put ("sendMessage", new java.lang.Integer (1));
    _methods.put ("sendInterMessage", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Cell/Station/registerTube
       {
         String number = in.read_string ();
         boolean $result = false;
         $result = this.registerTube (number);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Cell/Station/sendMessage
       {
         String fromNumber = in.read_string ();
         String toNumber = in.read_string ();
         String text = in.read_string ();
         boolean $result = false;
         $result = this.sendMessage (fromNumber, toNumber, text);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Cell/Station/sendInterMessage
       {
         String fromNumber = in.read_string ();
         String toNumber = in.read_string ();
         String fromStation = in.read_string ();
         String text = in.read_string ();
         boolean $result = false;
         $result = this.sendInterMessage (fromNumber, toNumber, fromStation, text);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Cell/Station:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Station _this() 
  {
    return StationHelper.narrow(
    super._this_object());
  }

  public Station _this(org.omg.CORBA.ORB orb) 
  {
    return StationHelper.narrow(
    super._this_object(orb));
  }


} // class StationPOA
