package ru.bmstu.rk6.cell.stub;


/**
* Cell/unauthorisedException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Wednesday, December 14, 2011 10:06:30 PM MSK
*/

public final class unauthorisedException extends org.omg.CORBA.UserException
{

  public unauthorisedException ()
  {
    super(unauthorisedExceptionHelper.id());
  } // ctor


  public unauthorisedException (String $reason)
  {
    super(unauthorisedExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class unauthorisedException
