package Cell;


/**
* Cell/StationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Monday, December 12, 2011 7:02:05 PM MSK
*/


/* ýýýýýýýýý ýýýýýýý ýýýýýýý */
public interface StationOperations 
{

  /* ýýý ýýýýýýýýý ýýýýýý ýýýýýý ýýýýýýýýýýýý ýýýýýý TubeCallback */
  int register (Cell.TubeCallback objRef, String phoneNum);
  int registerStation (Cell.Station objRef, String stationName);

  /* ýýýýýýýýý ýýýýýýýýý message ýý ýýýýýý fromNum ý ýýýýýý toNum */
  int sendSMS (String fromNum, String toNum, String message);
  Cell.TubeCallback getOponent (String num);
} // interface StationOperations
