package Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Monday, December 12, 2011 7:02:05 PM MSK
*/


/* ýýýýýýýýý ýýýýýýý ýýýýýýý */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
