package Cell;


/**
* Cell/TubeCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* Monday, December 12, 2011 7:02:05 PM MSK
*/


/* ýýýýýýýýý ýýýýýýýýý ýýýýýý ýýýýýý */
public interface TubeCallbackOperations 
{

  /* ýýýýýýý ýýýýýýýýý message ýý ýýýýýý fromNum */
  int sendSMS (String fromNum, String message);

  /* ýýýýýýý ýýýý ýýýýý */
  String getNum ();
} // interface TubeCallbackOperations
